[package]
name = 'nessify'
version = '0.0.0'
edition = '2018'
license = 'MIT'

[dependencies]
clap = { version = '~2.32', default-features = false }
csv = '~1.0'
serde = { version = '~1.0', features = ['derive'] }
serde_derive = '~1.0'
