---
version: 2.1

executors:
  rust-nightly:
    docker:
      - image: docker.io/rustlang/rust:nightly-slim

  rust-latest:
    docker:
      - image: docker.io/rust:1.32.0-slim

commands:
  check:
    steps:
      - run: cargo check

  clippy:
    steps:
      - name: Install Clippy
        run: "rustup component add clippy || cargo install --git ssh://git@github.com/rust-lang/rust-clippy.git --force clippy"
      - run: cargo clippy --all-targets --all-features -- -D warnings

jobs:
  check-nightly:
    executor: rust-nightly
    steps:
      - checkout
      - check

  clippy-nightly:
    executor: rust-nightly
    steps:
      - checkout
      - clippy

workflows:
  version: 2
  commit:
    jobs:
      - check-nightly
      - clippy-nightly
