---
version: 2.1

executors:
  rust-nightly:
    docker:
      - image: docker.io/rustlang/rust:nightly-slim

  rust-latest:
    docker:
      - image: docker.io/rust:1.32.0-slim

commands:
  check:
    steps:
      - run: cargo check

jobs:
  check-nightly:
    executor: rust-nightly
    steps:
      - checkout
      - check

workflows:
  version: 2
  commit:
    jobs:
      - check-nightly
