---
version: 2.1

executors:
  rust-nightly:
    docker:
      - image: docker.io/rustlang/rust:nightly-slim

  rust-latest:
    docker:
      - image: docker.io/rust:1.32.0-slim

commands:
  check:
    steps:
      - run: cargo check

  clippy:
    description: Run Clippy
    steps:
      - run: rustup component add clippy || cargo install --git ssh://git@github.com/rust-lang/rust-clippy.git --force clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings

  fmt:
    steps:
      - run: rustup component add rustfmt-preview
      - run: cargo fmt --all -- --check

jobs:
  check-nightly:
    executor: rust-nightly
    steps:
      - checkout
      - check

  check-latest:
    executor: rust-latest
    steps:
      - checkout
      - check

  clippy-nightly:
    executor: rust-nightly
    steps:
      - checkout
      - clippy

  clippy-latest:
    executor: rust-latest
    steps:
      - checkout
      - clippy
  fmt:
    executor: rust-nightly
    steps:
      - checkout
      - fmt


workflows:
  version: 2
  commit:
    jobs:
      - check-nightly
      - check-latest
      - clippy-nightly
      - clippy-latest
